# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


production:
  qiniu_access_key: TYBurzNuy6Rok1mdl9Q63AJyPxDcPK7FEA4MWurB  # 你的 qiniu AccessKey

  qiniu_secret_key: Q81jNwVOIgLlHBeIWHhMib9BtBR4F5gA-udUa-pz  # 你的 qiniu SecretKey

  qiniu_bucket: jdstore  # 你的 qiniu bucket

  qiniu_bucket_domain: oqgnjaxh1.bkt.clouddn.com  # 你的 qiniu bucket domain

  SEND_CLOUD_USER_NAME: "kerzzi_test_1nSTUP"  # 你的 API_USER

  SEND_CLOUD_USER_KEY: "ZlGXq8JTu59dkLsI"  # 你的 API_KEY

  QINIU_ACCESS_KEY: TYBurzNuy6Rok1mdl9Q63AJyPxDcPK7FEA4MWurB

  QINIU_SECRET_KEY: Q81jNwVOIgLlHBeIWHhMib9BtBR4F5gA-udUa-pz


development:
  qiniu_access_key: TYBurzNuy6Rok1mdl9Q63AJyPxDcPK7FEA4MWurB  # 你的 qiniu AccessKey

  qiniu_secret_key: Q81jNwVOIgLlHBeIWHhMib9BtBR4F5gA-udUa-pz  # 你的 qiniu SecretKey

  qiniu_bucket: jdstore  # 你的 qiniu bucket

  qiniu_bucket_domain: oqgnjaxh1.bkt.clouddn.com  # 你的 qiniu bucket domain

  SEND_CLOUD_USER_NAME: "kerzzi_test_1nSTUP"  # 你的 API_USER

  SEND_CLOUD_USER_KEY: "ZlGXq8JTu59dkLsI"  # 你的 API_KEY

  QINIU_ACCESS_KEY: TYBurzNuy6Rok1mdl9Q63AJyPxDcPK7FEA4MWurB

  QINIU_SECRET_KEY: Q81jNwVOIgLlHBeIWHhMib9BtBR4F5gA-udUa-pz
